In [37]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

PREPROCESSING DATA

In [38]:
training_data,validation_data = tf.keras.utils.image_dataset_from_directory(
    'PlantVillage',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=27,
    validation_split= 0.2,
    subset='both',
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
   
)

Found 20638 files belonging to 15 classes.
Using 16511 files for training.
Using 4127 files for validation.


In [39]:
training_data

<_BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 15), dtype=tf.float32, name=None))>

In [40]:
for x,y in training_data:
    print(x, x.shape)
    print(y, y.shape)
    break

tf.Tensor(
[[[[115.   107.   130.  ]
   [117.5  109.5  132.5 ]
   [120.   112.   135.  ]
   ...
   [126.25 118.25 142.25]
   [120.   112.   136.  ]
   [117.25 109.25 133.25]]

  [[117.25 109.25 132.25]
   [119.25 111.25 134.25]
   [121.   113.   136.  ]
   ...
   [126.   118.   142.  ]
   [122.75 114.75 138.75]
   [125.25 117.25 141.25]]

  [[111.5  103.5  126.5 ]
   [114.25 106.25 129.25]
   [122.25 114.25 137.25]
   ...
   [122.25 114.25 138.25]
   [122.75 114.75 138.75]
   [128.5  120.5  144.5 ]]

  ...

  [[100.75  92.75 113.75]
   [ 97.    89.   110.  ]
   [ 93.    85.   106.  ]
   ...
   [ 92.5   84.5  107.5 ]
   [ 94.5   86.5  109.5 ]
   [ 96.    88.   111.  ]]

  [[ 97.5   89.5  110.5 ]
   [ 93.5   85.5  106.5 ]
   [ 99.25  91.25 112.25]
   ...
   [ 92.25  84.25 107.25]
   [ 97.25  89.25 112.25]
   [ 91.    83.   106.  ]]

  [[ 99.5   91.5  112.5 ]
   [108.5  100.5  121.5 ]
   [104.75  96.75 117.75]
   ...
   [ 93.25  85.25 108.25]
   [100.25  92.25 115.25]
   [ 96.25  88.25 11

## Building Model

In [41]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
from tensorflow.keras.models import Sequential

In [42]:
model = Sequential()

In [43]:
model.add(Conv2D(filters=32,kernel_size=3, padding='same', activation='relu', input_shape=(128,128,3) ))
model.add(Conv2D(filters=32,kernel_size=3, activation='relu',  ))
model.add(MaxPool2D(pool_size=2, strides=2))

In [44]:
model.add(Conv2D(filters=64,kernel_size=3, padding='same', activation='relu' ))
model.add(Conv2D(filters=64,kernel_size=3, activation='relu',  ))
model.add(MaxPool2D(pool_size=2, strides=2))

In [45]:
model.add(Conv2D(filters=128,kernel_size=3, padding='same', activation='relu' ))
model.add(Conv2D(filters=128,kernel_size=3, activation='relu',  ))
model.add(MaxPool2D(pool_size=2, strides=2))

In [46]:
model.add(Conv2D(filters=256,kernel_size=3, padding='same', activation='relu',  ))
model.add(Conv2D(filters=256,kernel_size=3, activation='relu',  ))
model.add(MaxPool2D(pool_size=2, strides=2))

In [47]:
model.add(Conv2D(filters=512,kernel_size=3, padding='same', activation='relu' ))
model.add(Conv2D(filters=512,kernel_size=3, activation='relu',  ))
model.add(MaxPool2D(pool_size=2, strides=2))

In [48]:
model.add(Dropout(0.25))

In [49]:
model.add(Flatten())

In [50]:
model.add(Dense(units=1500, activation ='relu'))

In [51]:
model.add(Dropout(0.4))

In [52]:
model.add(Dense(units=15, activation='softmax',))

Compile the model

In [53]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [54]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 128, 128, 32)      896       
                                                                 
 conv2d_9 (Conv2D)           (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 63, 63, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_10 (Conv2D)          (None, 63, 63, 64)        18496     
                                                                 
 conv2d_11 (Conv2D)          (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 30, 30, 64)        0         
 g2D)                                                 

In [ ]:
training_history = model.fit(x=training_data, validation_data=validation_data, epochs=10)

Epoch 1/10


516/516 [==============================] - 2465s 5s/step - loss: 1.4389 - accuracy: 0.5352 - val_loss: 0.6742 - val_accuracy: 0.7621
Epoch 2/10
516/516 [==============================] - 2216s 4s/step - loss: 0.6881 - accuracy: 0.7689 - val_loss: 0.6236 - val_accuracy: 0.7819
Epoch 3/10
204/516 [==========>...................] - ETA: 20:31 - loss: 0.4794 - accuracy: 0.8392

MODEL EVALUATION

In [ ]:
## Saving Model

model.save("trained_model.keras")

In [ ]:
##Recording History

import json
with open('training_hist.json', 'w') as f:
    json.dump(training_history.history, f)

In [ ]:
#Model Evaluation on training set

train_loss, train_acc = model.evaluate(training_data)

In [ ]:
#Model Evaluation on training set

val_loss, val_acc = model.evaluate(validation_data)

In [ ]:
training_history = model.fit(x=training_data, validation_data=validation_data, epochs=15)

ACCURACY VISUALIZATION

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs, training_history.history['accuracy'], color='red', label='Training accuracy')
plt.plot(epochs, training_history.history['val_accuracy'], color='blue', label='Training accuracy')
plt.xlabel('No of Epochs')
plt.ylabel('Accuracy result')
plt.title('visualization of Accuracy Result')
plt.legend()
plt.show()